import type { RefObject } from 'react';
import type { ConsultationTopic, PetConsultationRequest, PetConsultationResponse } from '../../types/consultation';

const topicLabels: Record<ConsultationTopic, string> = { poop: 'うんちについて', meal: 'ごはんについて', walk: 'さんぽについて', overall: '全体的な体調について', other: 'その他' };

function AnswerList({ title, items, urgent = false }: { title: string; items: string[]; urgent?: boolean }) {
	return <section className={`rounded-2xl border p-4 ${urgent ? 'border-amber-200 bg-amber-50/70' : 'border-border-soft bg-white'}`}><h4 className="text-sm font-semibold text-slate-800">{title}</h4><ul className="mt-2 space-y-2 text-sm leading-relaxed text-slate-600">{items.map((item) => <li key={item} className="flex gap-2"><span aria-hidden="true" className="mt-2 size-1.5 shrink-0 rounded-full bg-brand-primary" />{item}</li>)}</ul></section>;
}

export function ConsultationAnswer({ request, response, answerRef, onEdit, onReset }: { request: PetConsultationRequest; response: PetConsultationResponse; answerRef: RefObject<HTMLElement | null>; onEdit: () => void; onReset: () => void }) {
	return <article ref={answerRef} tabIndex={-1} aria-live="polite" aria-labelledby="consult-answer-title" className="pc-card p-5 outline-none focus-visible:ring-2 focus-visible:ring-brand-sky"><p className="text-xs font-semibold text-brand-primary">記録をもとにした回答</p><h3 id="consult-answer-title" className="mt-1 text-xl font-semibold text-slate-800">{topicLabels[request.topic]}</h3><dl className="mt-3 space-y-1 text-sm"><div><dt className="inline text-slate-400">対象期間：</dt><dd className="inline text-slate-600">{request.period.label}</dd></div><div><dt className="inline text-slate-400">相談内容：</dt><dd className="inline break-words text-slate-600">{request.concern}</dd></div></dl><p className="mt-4 rounded-2xl bg-brand-subtle p-4 text-sm leading-relaxed text-slate-700">{response.summary}</p><div className="mt-4 space-y-3"><AnswerList title="記録から読み取れること" items={response.observations} /><AnswerList title="自宅で確認したいポイント" items={response.checkPoints} /><AnswerList title="動物病院へ相談する目安" items={response.veterinaryGuidance} /><AnswerList title="緊急性が高い可能性があるサイン" items={response.urgentSigns} urgent /><AnswerList title="追加で記録すると役立つこと" items={response.suggestedRecords} /></div><div className="mt-4 rounded-2xl border border-border-soft bg-slate-50 p-4 text-xs leading-relaxed text-slate-600"><p>{response.disclaimer}</p><p className="mt-2 font-semibold text-slate-700">呼吸が苦しそう、意識がもうろうとしている、大量の出血、けいれんなど緊急性が高い症状がある場合は、この機能の回答を待たず、動物病院へ連絡してください。</p></div><div className="mt-5 grid grid-cols-2 gap-2.5"><button type="button" onClick={onEdit} className="pc-button-secondary px-3 text-sm">相談内容を編集</button><button type="button" onClick={onReset} className="pc-button-primary px-3 text-sm">もう一度相談する</button></div></article>;
}
