import { Check } from 'lucide-react';
import { useEffect, useRef, useState, type SyntheticEvent } from 'react';
import { GROOMING_SERVICES, type GroomingLocation, type GroomingLog, type GroomingService, type NewGroomingLog } from '../types/grooming';
import { isValidDateValue, optionalText } from '../utils/careLogValidation';
import { normalizeGroomingServices } from '../utils/groomingStorage';

type Props = { initialValues?: GroomingLog; isEditing: boolean; onSubmit: (log: NewGroomingLog) => boolean; onCancelEdit: () => void };
const serviceLabels: Record<GroomingService, string> = { cut: 'カット', shampoo: 'シャンプー', nailTrim: '爪切り', earCleaning: '耳掃除', brushing: 'ブラッシング', dentalCare: 'デンタルケア', other: 'その他' };
const locationOptions: { value: GroomingLocation; label: string }[] = [{ value: 'salon', label: 'サロン' }, { value: 'home', label: '自宅' }, { value: 'other', label: 'その他' }];
function localDatetime(date = new Date()) { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }
function toInputDatetime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? localDatetime() : localDatetime(date); }

export function GroomingForm({ initialValues, isEditing, onSubmit, onCancelEdit }: Props) {
	const [datetime, setDatetime] = useState(localDatetime); const [services, setServices] = useState<GroomingService[]>([]); const [location, setLocation] = useState<GroomingLocation | ''>(''); const [salonName, setSalonName] = useState(''); const [otherService, setOtherService] = useState(''); const [cost, setCost] = useState(''); const [nextDate, setNextDate] = useState(''); const [memo, setMemo] = useState(''); const [attempted, setAttempted] = useState(false); const [submitting, setSubmitting] = useState(false); const lock = useRef(false);
	const costYen = cost === '' ? undefined : Number(cost); const costError = cost === '' || Number.isSafeInteger(costYen) && Number(costYen) >= 0 ? null : '0以上の整数で入力してください'; const servicesError = services.length ? null : 'ケア内容を1つ以上選んでください'; const otherError = services.includes('other') && !otherService.trim() ? 'その他のケア内容を入力してください' : null; const dateError = nextDate && !isValidDateValue(nextDate) ? '有効な日付を入力してください' : null;
	function reset() { setDatetime(localDatetime()); setServices([]); setLocation(''); setSalonName(''); setOtherService(''); setCost(''); setNextDate(''); setMemo(''); setAttempted(false); }
	useEffect(() => { if (!initialValues) { reset(); return; } setDatetime(toInputDatetime(initialValues.datetime)); setServices([...initialValues.services]); setLocation(initialValues.location ?? ''); setSalonName(initialValues.salonName ?? ''); setOtherService(initialValues.otherService ?? ''); setCost(initialValues.costYen === undefined ? '' : String(initialValues.costYen)); setNextDate(initialValues.nextCareDate ?? ''); setMemo(initialValues.memo ?? ''); setAttempted(false); }, [initialValues]);
	function toggleService(service: GroomingService) { setServices((current) => current.includes(service) ? current.filter((item) => item !== service) : [...current, service]); }
	function submit(e: SyntheticEvent<HTMLFormElement>) { e.preventDefault(); setAttempted(true); if (!datetime || servicesError || otherError || costError || dateError || lock.current) return; lock.current = true; setSubmitting(true); const normalized = normalizeGroomingServices(services); const saved = onSubmit({ datetime, services: normalized, ...(location ? { location } : {}), ...(optionalText(salonName) ? { salonName: optionalText(salonName) } : {}), ...(normalized.includes('other') && optionalText(otherService) ? { otherService: optionalText(otherService) } : {}), ...(costYen !== undefined ? { costYen } : {}), ...(nextDate ? { nextCareDate: nextDate } : {}), ...(optionalText(memo) ? { memo: optionalText(memo) } : {}) }); if (saved) reset(); setSubmitting(false); lock.current = false; }
	const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-brand-sky focus:ring-3 focus:ring-brand-mint/20';
	return <form onSubmit={submit} className="min-w-0 max-w-full space-y-4.5">
		<div className="min-w-0"><label htmlFor="grooming-datetime" className="mb-1.5 block text-sm font-semibold text-slate-700">実施日時</label><input id="grooming-datetime" type="datetime-local" required value={datetime} onChange={(e) => setDatetime(e.target.value)} className="datetime-input h-10 w-full rounded-xl border border-slate-200 bg-white py-2 pr-2.5 pl-3.5 text-sm text-slate-800 outline-none focus:border-brand-sky focus:ring-3 focus:ring-brand-mint/20" /></div>
		<fieldset><legend className="mb-2 block text-sm font-semibold text-slate-700">ケア内容</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{GROOMING_SERVICES.map((service) => { const selected = services.includes(service); return <button key={service} type="button" aria-pressed={selected} onClick={() => toggleService(service)} className={`flex min-h-11 items-center justify-center gap-1.5 rounded-xl border px-2 py-2 text-sm font-semibold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-sky ${selected ? 'border-brand-primary bg-brand-subtle text-brand-blue' : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'}`}>{selected && <Check size={15} strokeWidth={2.4} aria-hidden="true" />}{serviceLabels[service]}</button>; })}</div>{attempted && servicesError && <p className="mt-1.5 text-xs font-medium text-danger-strong">{servicesError}</p>}</fieldset>
		{services.includes('other') && <div><label htmlFor="grooming-other-service" className="mb-1.5 block text-sm font-semibold text-slate-700">その他のケア内容</label><input id="grooming-other-service" value={otherService} onChange={(e) => setOtherService(e.target.value)} aria-invalid={attempted && Boolean(otherError)} className={inputClass} />{attempted && otherError && <p className="mt-1.5 text-xs font-medium text-danger-strong">{otherError}</p>}</div>}
		<fieldset><legend className="mb-2 block text-sm font-semibold text-slate-700">実施場所</legend><div className="grid grid-cols-3 gap-2">{locationOptions.map((option) => <button key={option.value} type="button" aria-pressed={location === option.value} onClick={() => setLocation((current) => current === option.value ? '' : option.value)} className={`min-h-11 rounded-xl border px-2 text-sm font-semibold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-sky ${location === option.value ? 'border-brand-primary bg-brand-subtle text-brand-blue' : 'border-slate-200 bg-white text-slate-600'}`}>{option.label}</button>)}</div></fieldset>
		<div><label htmlFor="grooming-salon" className="mb-1.5 block text-sm font-semibold text-slate-700">サロン名</label><input id="grooming-salon" value={salonName} onChange={(e) => setSalonName(e.target.value)} className={inputClass} /></div>
		<div><label htmlFor="grooming-cost" className="mb-1.5 block text-sm font-semibold text-slate-700">費用</label><div className="relative"><input id="grooming-cost" type="number" inputMode="numeric" min={0} step={1} value={cost} onChange={(e) => setCost(e.target.value)} className={`${inputClass} pr-10`} /><span className="pointer-events-none absolute inset-y-0 right-3.5 flex items-center text-sm text-slate-400">円</span></div>{attempted && costError && <p className="mt-1.5 text-xs font-medium text-danger-strong">{costError}</p>}</div>
		<div><label htmlFor="grooming-next" className="mb-1.5 block text-sm font-semibold text-slate-700">次回予定日</label><input id="grooming-next" type="date" value={nextDate} onChange={(e) => setNextDate(e.target.value)} className={inputClass} />{attempted && dateError && <p className="mt-1.5 text-xs font-medium text-danger-strong">{dateError}</p>}</div>
		<div><label htmlFor="grooming-memo" className="mb-1.5 block text-sm font-semibold text-slate-700">メモ</label><textarea id="grooming-memo" rows={3} value={memo} onChange={(e) => setMemo(e.target.value)} className={`${inputClass} resize-none`} /></div>
		<div className="space-y-2.5"><button type="submit" disabled={submitting} className="pc-button-primary w-full px-5 text-base">{submitting ? '保存中…' : isEditing ? '更新する' : '記録する'}</button>{isEditing && <button type="button" onClick={() => { reset(); onCancelEdit(); }} className="min-h-11 w-full rounded-xl text-sm font-semibold text-slate-500 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-brand-sky">編集をキャンセル</button>}</div>
	</form>;
}
