import { useEffect, useRef, useState, type SyntheticEvent } from 'react';
import type { NewVaccineLog, VaccineLog } from '../types/vaccine';
import { isValidDateValue, optionalText } from '../utils/careLogValidation';

type Props = { initialValues?: VaccineLog; isEditing: boolean; onSubmit: (log: NewVaccineLog) => boolean; onCancelEdit: () => void };
function localDatetime(date = new Date()) { const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }
function toInputDatetime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? localDatetime() : localDatetime(date); }

export function VaccineForm({ initialValues, isEditing, onSubmit, onCancelEdit }: Props) {
	const [datetime, setDatetime] = useState(localDatetime); const [vaccineName, setVaccineName] = useState(''); const [hospitalName, setHospitalName] = useState(''); const [nextDate, setNextDate] = useState(''); const [cost, setCost] = useState(''); const [memo, setMemo] = useState(''); const [attempted, setAttempted] = useState(false); const [submitting, setSubmitting] = useState(false); const lock = useRef(false);
	const costYen = cost === '' ? undefined : Number(cost); const costError = cost === '' || Number.isSafeInteger(costYen) && Number(costYen) >= 0 ? null : '0以上の整数で入力してください'; const nameError = vaccineName.trim() ? null : 'ワクチン名を入力してください'; const dateError = nextDate && !isValidDateValue(nextDate) ? '有効な日付を入力してください' : null;
	function reset() { setDatetime(localDatetime()); setVaccineName(''); setHospitalName(''); setNextDate(''); setCost(''); setMemo(''); setAttempted(false); }
	useEffect(() => { if (!initialValues) { reset(); return; } setDatetime(toInputDatetime(initialValues.datetime)); setVaccineName(initialValues.vaccineName); setHospitalName(initialValues.hospitalName ?? ''); setNextDate(initialValues.nextVaccinationDate ?? ''); setCost(initialValues.costYen === undefined ? '' : String(initialValues.costYen)); setMemo(initialValues.memo ?? ''); setAttempted(false); }, [initialValues]);
	function submit(e: SyntheticEvent<HTMLFormElement>) { e.preventDefault(); setAttempted(true); if (!datetime || nameError || costError || dateError || lock.current) return; lock.current = true; setSubmitting(true); const saved = onSubmit({ datetime, vaccineName: vaccineName.trim(), ...(optionalText(hospitalName) ? { hospitalName: optionalText(hospitalName) } : {}), ...(nextDate ? { nextVaccinationDate: nextDate } : {}), ...(costYen !== undefined ? { costYen } : {}), ...(optionalText(memo) ? { memo: optionalText(memo) } : {}) }); if (saved) reset(); setSubmitting(false); lock.current = false; }
	const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-brand-sky focus:ring-3 focus:ring-brand-mint/20';
	return <form onSubmit={submit} className="min-w-0 max-w-full space-y-4.5">
		<div className="min-w-0"><label htmlFor="vaccine-datetime" className="mb-1.5 block text-sm font-semibold text-slate-700">接種日時</label><input id="vaccine-datetime" type="datetime-local" required value={datetime} onChange={(e) => setDatetime(e.target.value)} className="datetime-input h-10 w-full rounded-xl border border-slate-200 bg-white py-2 pr-2.5 pl-3.5 text-sm text-slate-800 outline-none focus:border-brand-sky focus:ring-3 focus:ring-brand-mint/20" /></div>
		<div><label htmlFor="vaccine-name" className="mb-1.5 block text-sm font-semibold text-slate-700">ワクチン名</label><input id="vaccine-name" required value={vaccineName} onChange={(e) => setVaccineName(e.target.value)} aria-invalid={attempted && Boolean(nameError)} placeholder="ワクチン名を入力" className={inputClass} />{attempted && nameError && <p className="mt-1.5 text-xs font-medium text-danger-strong">{nameError}</p>}</div>
		<div><label htmlFor="vaccine-hospital" className="mb-1.5 block text-sm font-semibold text-slate-700">病院名</label><input id="vaccine-hospital" value={hospitalName} onChange={(e) => setHospitalName(e.target.value)} className={inputClass} /></div>
		<div><label htmlFor="vaccine-next" className="mb-1.5 block text-sm font-semibold text-slate-700">次回予定日</label><input id="vaccine-next" type="date" value={nextDate} onChange={(e) => setNextDate(e.target.value)} className={inputClass} />{attempted && dateError && <p className="mt-1.5 text-xs font-medium text-danger-strong">{dateError}</p>}</div>
		<div><label htmlFor="vaccine-cost" className="mb-1.5 block text-sm font-semibold text-slate-700">費用</label><div className="relative"><input id="vaccine-cost" type="number" inputMode="numeric" min={0} step={1} value={cost} onChange={(e) => setCost(e.target.value)} className={`${inputClass} pr-10`} /><span className="pointer-events-none absolute inset-y-0 right-3.5 flex items-center text-sm text-slate-400">円</span></div>{attempted && costError && <p className="mt-1.5 text-xs font-medium text-danger-strong">{costError}</p>}</div>
		<div><label htmlFor="vaccine-memo" className="mb-1.5 block text-sm font-semibold text-slate-700">メモ</label><textarea id="vaccine-memo" rows={3} value={memo} onChange={(e) => setMemo(e.target.value)} className={`${inputClass} resize-none`} /></div>
		<div className="space-y-2.5"><button type="submit" disabled={submitting} className="pc-button-primary w-full px-5 text-base">{submitting ? '保存中…' : isEditing ? '更新する' : '記録する'}</button>{isEditing && <button type="button" onClick={() => { reset(); onCancelEdit(); }} className="min-h-11 w-full rounded-xl text-sm font-semibold text-slate-500 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-brand-sky">編集をキャンセル</button>}</div>
	</form>;
}
